//! Parity tests against the cedar-detect reference implementation.
//!
//! The golden fixture in `tests/data/cedar_goldens_bin1_sigma8.json` was
//! generated by running the upstream `test_cedar_detect` binary on
//! `reference-solutions/cedar-detect/test_data` with `binning = 1` and
//! `sigma = 8.0`. These tests load the same JPEG images, run our
//! `detect_stars`, and assert that centroids and brightest-first ordering
//! match within the spec tolerance.

use std::collections::HashMap;
use std::path::PathBuf;

use image::ImageReader;
use serde::Deserialize;
use star_detection::detect_stars;

const GOLDEN_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/cedar_goldens_bin1_sigma8.json");
const TEST_DATA_DIR: &str = "../../reference-solutions/cedar-detect/test_data";
const TOLERANCE_PX: f64 = 0.1;
const SIGMA: f64 = 8.0;
const BINNING: usize = 1;

#[derive(Debug, Deserialize)]
struct GoldenImage {
    width: u32,
    height: u32,
    stars: Vec<GoldenStar>,
}

#[derive(Debug, Deserialize, Clone)]
struct GoldenStar {
    x: f64,
    y: f64,
}

fn load_goldens() -> HashMap<String, GoldenImage> {
    let text = std::fs::read_to_string(GOLDEN_PATH).expect("read golden fixture");
    serde_json::from_str(&text).expect("parse golden fixture")
}

fn load_image(name: &str) -> (Vec<u8>, usize, usize) {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push(TEST_DATA_DIR);
    path.push(name);
    let img = ImageReader::open(&path)
        .unwrap_or_else(|e| panic!("open {}: {}", path.display(), e))
        .decode()
        .unwrap_or_else(|e| panic!("decode {}: {}", path.display(), e))
        .to_luma8();
    let (width, height) = img.dimensions();
    (img.into_raw(), width as usize, height as usize)
}

/// Match detected stars to golden stars by nearest neighbor within tolerance.
/// Returns (matched pairs, unmatched detected, unmatched golden).
fn match_stars(detected: &[(f64, f64)], golden: &[GoldenStar], tol: f64) -> (Vec<(usize, usize)>, Vec<usize>, Vec<usize>) {
    let mut pairs = Vec::new();
    let mut used_golden = vec![false; golden.len()];
    let mut used_detected = vec![false; detected.len()];

    for (di, &(dx, dy)) in detected.iter().enumerate() {
        let mut best: Option<(usize, f64)> = None;
        for (gi, g) in golden.iter().enumerate() {
            if used_golden[gi] {
                continue;
            }
            let dist_sq = (dx - g.x).powi(2) + (dy - g.y).powi(2);
            if dist_sq > tol * tol {
                continue;
            }
            if best.map_or(true, |(_, bd)| dist_sq < bd) {
                best = Some((gi, dist_sq));
            }
        }
        if let Some((gi, _)) = best {
            pairs.push((di, gi));
            used_golden[gi] = true;
            used_detected[di] = true;
        }
    }

    let unmatched_detected: Vec<usize> = used_detected.iter().enumerate().filter(|(_, u)| !**u).map(|(i, _)| i).collect();
    let unmatched_golden: Vec<usize> = used_golden.iter().enumerate().filter(|(_, u)| !**u).map(|(i, _)| i).collect();
    (pairs, unmatched_detected, unmatched_golden)
}

#[test]
fn cedar_detect_parity_on_all_reference_images() {
    let goldens = load_goldens();
    let mut failures = Vec::new();

    for (name, golden) in goldens {
        let (image, width, height) = load_image(&name);
        let stars = detect_stars(&image, width, height, SIGMA, BINNING, false, false);
        let detected: Vec<(f64, f64)> = stars.iter().map(|s| (s.x, s.y)).collect();
        let golden_coords: Vec<GoldenStar> = golden.stars.clone();

        let (pairs, unmatched_detected, unmatched_golden) = match_stars(&detected, &golden_coords, TOLERANCE_PX);

        if !unmatched_golden.is_empty() || !unmatched_detected.is_empty() {
            failures.push(format!(
                "{}: matched {} / golden {} / detected {}; unmatched golden {}, unmatched detected {}",
                name,
                pairs.len(),
                golden_coords.len(),
                detected.len(),
                unmatched_golden.len(),
                unmatched_detected.len()
            ));
        }
    }

    assert!(failures.is_empty(), "parity failures:\n{}", failures.join("\n"));
}
